### ISSUE TITLE
Data are not being saved to DB

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/GrowDataApp#5]
The app crashes when calling `cmd.ExecuteNonQuery();` with following exception:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
Jan 26 12:42:10 work-wps dotnet-example[27298]:       An unhandled exception has occurred while executing the request.
Jan 26 12:42:10 work-wps dotnet-example[27298]: MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution.
Jan 26 12:42:10 work-wps dotnet-example[27298]:  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset.
Jan 26 12:42:10 work-wps dotnet-example[27298]:  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed.
Jan 26 12:42:10 work-wps dotnet-example[27298]:  ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out.
Jan 26 12:42:10 work-wps dotnet-example[27298]:  ---> System.Net.Sockets.SocketException (110): Connection timed out
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    --- End of inner exception stack trace ---
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at System.Net.Security.SslStream.FillBufferAsync[TReadAdapter](TReadAdapter adapter, Int32 minSize)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at GrowDataApp.Core.Dao.DbContext.Save(GrowDataItem growDataItem) in C:\Users\zdenda.DESKTOP-KS2IS4C\prg\GrowDataApp\Core\Dao\DbContext.cs:line 52
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at lambda_method(Closure , Object , Object[] )
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object control
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
Jan 26 12:42:10 work-wps dotnet-example[27298]: --- End of stack trace from previous location where exception was thrown ---
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Jan 26 12:42:10 work-wps dotnet-example[27298]: --- End of stack trace from previous location where exception was thrown ---
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, O
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jan 26 12:42:10 work-wps dotnet-example[27298]:    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Log obtained from `journalctl -u growerapp`.

**Comment by Cajova-Houba** [comment]
[Docs ragarding ASP.NET logging configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0) which may come handy when investigating this.
